name: Standalone

on:
  push:
    branches:
      - master
      - main
  pull_request:
    branches:
      - master
      - main

env:
  CPM_SOURCE_CACHE: ${{ github.workspace }}/cpm_modules

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/cache@v2
        with:
          path: "**/cpm_modules"
          key: ${{ github.workflow }}-cpm-modules-${{ hashFiles('**/CMakeLists.txt', '**/*.cmake') }}

      - name: Install Antlr4
        run: curl -O https://www.antlr.org/download/antlr-4.9.3-complete.jar && sudo mv antlr-4.9.3-complete.jar /usr/local/lib/antlr-4.9.3-complete.jar

      - name: configure
        run: cmake -Sstandalone -Bbuild -DANTLR_EXECUTABLE=/usr/local/lib/antlr-4.9.3-complete.jar -DCMAKE_BUILD_TYPE=Debug -DCMAKE_BUILD_TYPE=Debug

      - name: build
        run: cmake --build build -j4
